APPLY_FIXES: all
DISABLE:
  - CLOUDFORMATION
  - CSS
  - EDITORCONFIG
  - JAVASCRIPT
  - TEKTON
DISABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_TRUFFLEHOG
DISABLE_ERRORS_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_PYRIGHT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - REPOSITORY_SEMGREP
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - COPYPASTE_JSCPD
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TFLINT
  - SPELL_CSPELL
  - SPELL_PROSELINT
  - SPELL_MISSPELL
  - SPELL_VALE

PRE_COMMANDS:
  - command: echo "This is MegaLinter PRE_COMMAND on own MegaLinter ! :)"
    cwd: "root"
POST_COMMANDS:
  - command: echo "This is MegaLinter POST_COMMAND on own MegaLinter ! :)"
    cwd: "workspace"