name: Terraform plan and apply
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  plan:
    if: "${{ github.event_name == 'pull_request' }}"
    uses: torivara/reusable-templates/.github/workflows/terraform-plan.yaml@main
    with:
      environment: production
      workingDir: ./
      tfDocsDirectories: "./platform, ./modules"
      tfLintConfigFile: "platform/.tflint.hcl"
    secrets: inherit

  apply:
    if: "${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}"
    uses: torivara/reusable-templates/.github/workflows/terraform-apply.yaml@main
    with:
      environment: production
      workingDir: ./
    secrets: inherit